1. 1 - dimensional array

In [1]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


2. 2 - dimensional array. 

In [2]:
import numpy as np

b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


3. creating rows and columns with zeros.

In [3]:
import numpy as np

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

4. Intervals.

In [4]:
import numpy as np

np.arange(1,10,2)

array([1, 3, 5, 7, 9])

5. certain amount of numbers accordingly.

In [5]:
import numpy as np

np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])