1. 1 - dimensional array

In [1]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


2. 2 - dimensional array. 

In [2]:
import numpy as np

b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


3. creating rows and columns with zeros.

In [3]:
import numpy as np

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

4. Intervals.

In [4]:
import numpy as np

np.arange(1,10,2)

array([1, 3, 5, 7, 9])

5. certain amount of numbers accordingly.

In [5]:
import numpy as np

np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

6. fill a specific number

In [3]:
import numpy as np
np.full((2,3),6)

array([[6, 6, 6],
       [6, 6, 6]])

7. adding random number

In [5]:
import numpy as np
np.random.random((2,3))

array([[0.90304283, 0.76406536, 0.46584468],
       [0.81387936, 0.25695411, 0.30308794]])

8. checking the size

In [7]:
import numpy as np
a = np.array([[2,3,4], [4,4,6]])
print(a.shape)

(2, 3)


9. resize the array

In [12]:
import numpy as np
a = np.array([[2,3,4], [4,4,6]])
a.shape = (3,2)
print(a)

[[2 3]
 [4 4]
 [4 6]]


10. return the dimension of the array

In [14]:
a = np.arange(25)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


11. find the numbers of elements in an array

In [15]:
print(a.size)

25


12. find the datatype of the array

In [ ]:
import numpy as np
a = np.arange(24, dtype=float)
print(a.dtype)  ???

float64


13. mathematics sum

In [ ]:
import numpy as np
np.sum([10, 20]) ????

np.int64(30)

In [ ]:
a,b = 10, 20
np.sum([a,b]) ????

np.int64(30)

In [23]:
np.sum([[1,2],[5,6]], axis = 0)

array([6, 8])

In [24]:
np.sum([[1,2],[5,6]], axis = 1)

array([ 3, 11])

In [ ]:
np.sum([[1,2],[5,6]]) ????

np.int64(14)

14. substract

In [ ]:
np.subtract(10,20) ???

np.int64(-10)

15. multiply

In [ ]:
np.multiply(10,20) ????

np.int64(200)

16. divide

In [ ]:
np.divide(20,10) ????

np.float64(2.0)

17. exponent, square root, sin, cos, log

In [30]:
a = np.array([2,4,6])
b = np.array([1,2,3])
print('Exponent: ', np.exp(a))
print("Square root : ", np.sqrt(a))
print("Sin : ", np.sin(a))
print("Cos : ", np.cos(a))
print("Log : ", np.log(a))

Exponent:  [  7.3890561   54.59815003 403.42879349]
Square root :  [1.41421356 2.         2.44948974]
Sin :  [ 0.90929743 -0.7568025  -0.2794155 ]
Cos :  [-0.41614684 -0.65364362  0.96017029]
Log :  [0.69314718 1.38629436 1.79175947]


18. equal or not equal 

In [34]:
a = [1,2,4]
b = [2,4,4]
c = [1,2,4]
np.equal(a,b)


array([False, False,  True])

In [33]:
a = [1,2,4]
b = [2,4,4]
c = [1,2,4]
np.array_equal(a,c)

True

19. aggregate function

In [36]:
a = [1,2,4]
b = [2,4,4]
c = [1,2,4]
print("Sum: ",np.sum(a))
print("Minimum Value: ",np.min(a))
print("Mean: ",np.mean(a))
print("Median: ",np.median(a))
print("Coorelation Coefficient: ",np.corrcoef(a))
print("Standard Deviation: ",np.std(a))


Sum:  7
Minimum Value:  1
Mean:  2.3333333333333335
Median:  2.0
Coorelation Coefficient:  1.0
Standard Deviation:  1.247219128924647


20. concept of broadcasting

In [38]:
import numpy as np
a = np.array([[0,0,0],[1,2,3],[4,5,6],[5,6,7]])
b = np.array([[0,1,2]])
print("First Array: \n",a,'\n')
print("Second Array: \n",b,'\n')
print("First Array + Second Array: \n",a+b,'\n')

First Array: 
 [[0 0 0]
 [1 2 3]
 [4 5 6]
 [5 6 7]] 

Second Array: 
 [[0 1 2]] 

First Array + Second Array: 
 [[0 1 2]
 [1 3 5]
 [4 6 8]
 [5 7 9]] 



21. indexing and slicing.

In [39]:
a = ['m','o','n','t','y',' ','p','y','t','h','o','n']
a[2:9]

['n', 't', 'y', ' ', 'p', 'y', 't']

22. array manipulation

In [40]:
a = np.array([1,2,3])
b= np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [41]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
import numpy as np
a = np.arange(24)
print(a.ndim)
print(a)
b = a.reshape(6,4)
print(b)

1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
